CREATE TABLE users
(
    ID SERIAL NOT NULL PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Username VARCHAR UNIQUE NOT NULL,
    Password_hash VARCHAR NOT NULL
);

CREATE TABLE todo_lists
(
    ID SERIAL NOT NULL PRIMARY KEY,
    Title VARCHAR NOT NULL UNIQUE,
    Description VARCHAR NULL,
    User_ID INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users (ID) ON DELETE CASCADE
);

CREATE TABLE todo_items
(
    ID SERIAL NOT NULL PRIMARY KEY,
    Title VARCHAR NOT NULL UNIQUE,
    Description VARCHAR NULL,
    Done BOOLEAN NOT NULL DEFAULT FALSE,
    List_ID INT NOT NULL,
    FOREIGN KEY (List_ID) REFERENCES Todo_lists (ID) ON DELETE CASCADE
);

